# generates a rubocop todo file
# $ rubocop --auto-gen-config

# inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'Guardfile'
    - 'lib/tasks/**/*'
    - 'Gemfile'
    - 'bin/**/*'
    - 'spec/spec_helper.rb'
    - 'test/test_helper.rb'
    - 'Rakefile'

Style/StringLiterals:
  Enabled: false

Documentation:
  Enabled: false

# https://github.com/bbatsov/rubocop/issues/1238
Style/GuardClause:
  Enabled: false

# https://github.com/bbatsov/rubocop/issues/1238
Style/Next:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/ClassLength:
  CountComments: false
  Max: 500

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/LineLength:
  Max: 120
